name: Test Suite

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        
    name: Test on Node.js ${{ matrix.node-version }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Display Node.js and npm versions
      run: |
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"

    - name: Make runner.js executable
      run: chmod +x ./test/runner.js
      
    - name: Run test suite
      run: |
        echo "🚀 Starting pULID test suite..."
        node ./test/runner.js

  test-summary:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Test Summary
      run: |
        if [ "${{ needs.test.result }}" == "success" ]; then
          echo "✅ All tests passed across all Node.js versions!"
        else
          echo "❌ Some tests failed. Check the job logs for details."
          exit 1
        fi
